import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";
// Import your new components
import { Navbar } from "@/app/components/Navbar";
import { Footer } from "@/app/components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col min-h-screen`}
      >
        {/* === THIS IS THE LINE THAT WAS ADDED === */}
        {/* This component is invisible but listens for toast calls from any page */}
        <Toaster position="top-center" reverseOrder={false} />

        {/* 1. The Navbar remains at the top */}
        <Navbar />

        {/* 2. The main content of your pages will be rendered here */}
        <main className="flex-grow container mx-auto px-6 py-8">
          {children}
        </main>

        {/* 3. The Footer remains at the bottom */}
        <Footer />
      </body>
    </html>
  );
}
